#!/bin/bash -x 

UBOOT_SRC=$WORKSPACE
echo "Starting $0 !!"

install_path=/opt/analog
export PATH=$install_path/cces/$cces_version/ARM/arm-none-eabi/bin:$install_path/cces-linux-add-in/$uboot_version/ARM/arm-linux-gnueabi/bin:$PATH


## check out uboot

cd $UBOOT_SRC/../
rm -rf uboot uboot-sc5xx-$uboot_version uboot-sc5xx-$uboot_version.tar.gz && ls
mkdir -p $UBOOT_SRC/../uboot-sc5xx-$uboot_version/{bin,src}

cd $UBOOT_SRC/
git branch -a
echo "##### Jenkins Build Tag: $BUILD_TAG #####" > Version
echo "##### UBOOT Version #####################" >> Version
git log -1 >> Version
rm -rf $UBOOT_SRC/.git  $UBOOT_SRC/.gitignore

# Tar the uboot source code exclude the test_script
cp -r $UBOOT_SRC  $UBOOT_SRC/../uboot
rm -rf $UBOOT_SRC/../uboot/test_script

cd $UBOOT_SRC/../
tar zcf uboot-sc5xx-$uboot_version.tar.gz  uboot
md5sum uboot-sc5xx-$uboot_version.tar.gz >> $UBOOT_SRC/Version
mv uboot-sc5xx-$uboot_version.tar.gz  uboot-sc5xx-$uboot_version/src

# Change the UBOOT_SRC to /home/test/workspace/src/uboot/label/uboot
rm -rf $UBOOT_SRC/../uboot
mv $UBOOT_SRC  $UBOOT_SRC/../uboot

UBOOT_SRC=${UBOOT_SRC/%$NODE_NAME/uboot}

for i in 1 2 3 4;
do

if [ $i = 1 ] ; then
    board_type=sc589-ezkit
    config_param=sc589-ezkit_config
elif [ $i = 2 ] ; then
    board_type=sc584-ezkit
    config_param=sc584-ezkit_config
elif [ $i = 3 ] ; then
    board_type=sc573-ezkit
    config_param=sc573-ezkit_config
elif [ $i = 4 ] ; then
    board_type=sc589-mini
    config_param=sc589-mini_config
else
    echo "Unknown target board type $BOARD_TYPE."
    exit 2
fi

echo
echo "********************************************"
echo "Start building u-boot of $board_type ! "
cd $UBOOT_SRC
make distclean   #>/dev/null  2>&1
make clean  # >/dev/null  2>&1
make mrproper # >/dev/null  2>&1
make $config_param # >/dev/null  2>&1
make # >> $UBOOT_SRC/uboot_make_log  2>&1

if [ ! -e u-boot.bin ] && [ ! -e u-boot.ldr ] ; then
    exit 2
fi

[ -e arch/arm/cpu/armv7/sc58x/init.elf ] && cp arch/arm/cpu/armv7/sc58x/init.elf  $UBOOT_SRC/../uboot-sc5xx-$uboot_version/bin/init-${board_type}.elf
[ -e arch/arm/cpu/armv7/sc57x/init.elf ] && cp arch/arm/cpu/armv7/sc57x/init.elf  $UBOOT_SRC/../uboot-sc5xx-$uboot_version/bin/init-${board_type}.elf
[ -e u-boot ] && cp u-boot $UBOOT_SRC/../uboot-sc5xx-$uboot_version/bin/u-boot-${board_type}
[ -e u-boot.bin ] && cp u-boot.bin $UBOOT_SRC/../uboot-sc5xx-$uboot_version/bin/u-boot-${board_type}.bin
[ -e u-boot.ldr ] && cp u-boot.ldr $UBOOT_SRC/../uboot-sc5xx-$uboot_version/bin/u-boot-${board_type}.ldr  

done

cd $UBOOT_SRC/../
tar zcf uboot-sc5xx-$uboot_version.tar.gz  $UBOOT_SRC/../uboot-sc5xx-$uboot_version && pwd &&  cp uboot-sc5xx-$uboot_version.tar.gz /home/test

md5sum /home/test/uboot-sc5xx-$uboot_version.tar.gz

cd $UBOOT_SRC/test_script
./upload_package.exp uboot-sc5xx-$uboot_version.tar.gz  
./stage_svn_commit.exp uboot

rm -rf $UBOOT_SRC

exit
